all: button_controlled_pwm
button_controlled_pwm: button_controlled_pwm.o
gcc -o button_controlled_pwm.o
button_controlled_pwm.o: button_controlled_pwm.c
gcc -c button_controlled_pwm.c
clean:
rm button_controlled_pwm.o button_controlled_pwm
